export const brands = [
    {
      id: 0,
      supportedBrand: [
        { src: '/banner/Ten13.png' },
        { src: '/banner/investible.svg' },
        { src: '/banner/UNSW Sydney.svg' },
        { src: '/banner/USYD Genesis.svg' },
        { src: '/banner/Founders 10x Accelerator.svg' },
        { src: '/banner/airtree.svg' },
      ],
    },
    {
      id: 1,
      supportedBrand: [
        { src: '/banner/Ozito Industries Pty Ltd.svg' },
        { src: '/banner/Hankook.svg' },
        { src: '/banner/Sea Transport.svg' },
        { src: '/banner/A&I Coatings.svg' },
        { src: '/banner/K2 Systems.svg' },
        { src: '/banner/Juvo Solutions.svg' },
        { src: '/banner/A&J Australia.svg' },
        { src: '/banner/AF Accessories.svg' },
        { src: '/banner/Lomax Group Pty Ltd.svg' },
        { src: '/banner/Wise Networking.svg' },
        { src: '/banner/Mission Systems.svg' },
        { src: '/banner/Valiant Space.svg' },
      ],
    },
    {
      id: 2,
      supportedBrand: [
        { src: '/banner/Identitii Pty Ltd.svg' },
        { src: '/banner/Secure Code Warrior.svg' },
        { src: '/banner/Prophecy.svg' },
        { src: '/banner/EASI-square.svg' },
        { src: '/banner/Braintree Communications Pty Ltd.svg' },
        { src: '/banner/Tiliter Pty Ltd.svg' },
        { src: '/banner/Preezie.svg' },
        { src: '/banner/Picnic IP Pty Ltd.svg' },
        { src: '/banner/Mission Systems.svg' },
      ],
    },
    {
      id: 3,
      supportedBrand: [
        { src: '/banner/Cyclomedica.svg' },
        { src: '/banner/iiShield.svg' },
        { src: '/banner/Global Surgical Innovations Holdings Pty Ltd.svg' },
        { src: '/banner/Nuroflux.svg' },
        { src: '/banner/Alpinia Biopharm Pty Ltd.svg' },
      ],
    },
    {
      id: 1,
      supportedBrand: [
        { src: '/banner/Cyclomedica.svg' },
        { src: '/banner/Identitii Pty Ltd.svg' },
        { src: '/banner/Ozito Industries Pty Ltd.svg' },
        { src: '/banner/Secure Code Warrior.svg' },
        { src: '/banner/Prophecy.svg' },
        { src: '/banner/EASI-square.svg' },
        { src: '/banner/Hankook.svg' },
        { src: '/banner/Mortgage Choice.svg' },
        { src: '/banner/Sea Transport.svg' },
        { src: '/banner/Alpinia Biopharm Pty Ltd.svg' },
        { src: '/banner/Nick Scali.svg' },
        { src: '/banner/A&I Coatings.svg' },
        { src: '/banner/K2 Systems.svg' },
        { src: '/banner/Juvo Solutions.svg' },
        { src: '/banner/A&J Australia.svg' },
        { src: '/banner/AF Accessories.svg' },
        { src: '/banner/Braintree Communications Pty Ltd.svg' },
        { src: '/banner/Lomax Group Pty Ltd.svg' },
        { src: '/banner/Preezie.svg' },
        { src: '/banner/Picnic IP Pty Ltd.svg' },
      ],
    },
  ]