export const brands = [
  {
    id: 0,
    supportedBrand: [
      { src: '/banner/Ten13.png' },
      { src: '/banner/investible.svg' },
      { src: '/banner/UNSW Sydney.svg' },
      { src: '/banner/USYD Genesis.svg' },
      { src: '/banner/Founders 10x Accelerator.svg' },
      { src: '/banner/airtree.svg' },
    ],
  },
  {
    id: 1,
    supportedBrand: [
      { src: '/banner/Ozito Industries Pty Ltd.svg' },
      { src: '/banner/Hankook.svg' },
      { src: '/banner/Sea Transport.svg' },
      { src: '/banner/A&I Coatings.svg' },
      { src: '/banner/K2 Systems.svg' },
      { src: '/banner/Juvo Solutions.svg' },
      { src: '/banner/A&J Australia.svg' },
      { src: '/banner/AF Accessories.svg' },
      { src: '/banner/Lomax Group Pty Ltd.svg' },
      { src: '/banner/Wise Networking.svg' },
      { src: '/banner/Mission Systems.svg' },
      { src: '/banner/Valiant Space.svg' },
    ],
  },
  {
    id: 2,
    supportedBrand: [
      { src: '/banner/Identitii Pty Ltd.svg' },
      { src: '/banner/Secure Code Warrior.svg' },
      { src: '/banner/Prophecy.svg' },
      { src: '/banner/EASI-square.svg' },
      { src: '/banner/Braintree Communications Pty Ltd.svg' },
      { src: '/banner/Tiliter Pty Ltd.svg' },
      { src: '/banner/Preezie.svg' },
      { src: '/banner/Picnic IP Pty Ltd.svg' },
      { src: '/banner/Mission Systems.svg' },
    ],
  },
  {
    id: 3,
    supportedBrand: [
      { src: '/banner/Cyclomedica.svg' },
      { src: '/banner/iiShield.svg' },
      { src: '/banner/Global Surgical Innovations Holdings Pty Ltd.svg' },
      { src: '/banner/Nuroflux.svg' },
      { src: '/banner/Alpinia Biopharm Pty Ltd.svg' },
    ],
  },
  {
    id: 4,
    supportedBrand: [
      { src: '/banner/Cyclomedica.svg' },
      { src: '/banner/Identitii Pty Ltd.svg' },
      { src: '/banner/Ozito Industries Pty Ltd.svg' },
      { src: '/banner/Secure Code Warrior.svg' },
      { src: '/banner/Prophecy.svg' },
      { src: '/banner/EASI-square.svg' },
      { src: '/banner/Hankook.svg' },
      { src: '/banner/Mortgage Choice.svg' },
      { src: '/banner/Sea Transport.svg' },
      { src: '/banner/Alpinia Biopharm Pty Ltd.svg' },
      { src: '/banner/Nick Scali.svg' },
      { src: '/banner/A&I Coatings.svg' },
      { src: '/banner/K2 Systems.svg' },
      { src: '/banner/Juvo Solutions.svg' },
      { src: '/banner/A&J Australia.svg' },
      { src: '/banner/AF Accessories.svg' },
      { src: '/banner/Braintree Communications Pty Ltd.svg' },
      { src: '/banner/Lomax Group Pty Ltd.svg' },
      { src: '/banner/Preezie.svg' },
      { src: '/banner/Picnic IP Pty Ltd.svg' },
    ],
  },
  {
    id: 5,
    supportedBrand: [
      { src: '/banner/Slingshot Haulage.svg' },
      { src: '/banner/Wombat Timbers.svg' },
    ],
  },
  {
    id: 6,
    supportedBrand: [{ src: '/banner/Juvo Solutions.svg' }],
  },
  {
    id: 7,
    supportedBrand: [
      { src: '/banner/Identitii Pty Ltd.svg' },
      { src: '/banner/Mazooma.svg' },
      { src: '/banner/Picnic IP Pty Ltd.svg' },
      { src: '/banner/Spectrum Message Services.svg' },
    ],
  },
  {
    id: 8,
    supportedBrand: [
      { src: '/banner/JANDS.svg' },
      { src: '/banner/K-Hart International Pty Ltd.svg' },
      { src: '/banner/L3-Micreo Pty Ltd.svg' },
      { src: '/banner/Thomas Global Systems.svg' },
      { src: '/banner/WBS.svg' },
      { src: '/banner/ZTE.svg' },
    ],
  },
  {
    id: 9,
    supportedBrand: [
      { src: '/clients/logo-general-dynamics-ots.png' },
      { src: '/banner/Lockheed Martin.svg' },
      { src: '/banner/Mitsubishi Heavy Industries.svg' },
      { src: '/banner/NCS Multistage.svg' },
      { src: '/banner/Thomas Global Systems.svg' },
    ],
  },
  {
    id: 10,
    supportedBrand: [
      { src: '/banner/Covidien.svg' },
      { src: '/banner/Ethicon Endo-Surgery, Inc.svg' },
      { src: '/banner/Optimized Ortho.svg' },
      { src: '/banner/Source Energy Services.svg' },
      { src: '/banner/Syntheon.svg' },
    ],
  },
  {
    id: 11,
    supportedBrand: [
      { src: '/banner/Biometic GHTI.svg' },
      { src: '/banner/Covidien.svg' },
      { src: '/banner/Ethicon Endo-Surgery, Inc.svg' },
      { src: '/banner/Glycom.svg' },
      { src: '/banner/i2s.svg' },
      { src: '/banner/Ironwood.svg' },
      { src: '/banner/Lenswista.svg' },
      { src: '/banner/Optimized Ortho.svg' },
      { src: '/banner/Sunjin Beauty Science.svg' },
      { src: '/banner/Syntheon.svg' },
    ],
  },
  {
    id: 12,
    supportedBrand: [
      { src: '/banner/Cyclopharm Limited.svg' },
      { src: '/banner/Lockheed Martin.svg' },
      { src: '/banner/RedGarage.svg' },
      { src: '/banner/Thomas Electronics of Australia Pty Ltd.svg' },
    ],
  },
  {
    id: 13,
    supportedBrand: [
      { src: '/banner/E-nome.svg' },
      { src: '/banner/Identitii Pty Ltd.svg' },
      { src: '/banner/Penten.svg' },
      { src: '/banner/Quikser.svg' },
      { src: '/banner/Red Propaganda.svg' },
      { src: '/banner/Spectrum Message Services.svg' },
      { src: '/banner/Thomas Electronics of Australia Pty Ltd.svg' },
    ],
  },
]
