export const sideMenus = [
  {
    id: 1,
    name: 'Patent Service',
    img: '/menus/services/sideMenus/patent-service.svg',
    href: '/services',
  },
  {
    id: 2,
    name: 'Patent Specification',
    img: '/menus/services/sideMenus/patent-specifications.svg',
    href: '',
  },
  {
    id: 3,
    name: 'Trademark Service',
    img: '/menus/services/sideMenus/trademark-services.svg',
    href: '',
  },
  {
    id: 4,
    name: 'Ip Opporsitions & Disputes',
    img: '/menus/services/sideMenus/ip-oppositions.svg',
    href: '',
  },
  {
    id: 5,
    name: 'Bip Partners',
    img: '/menus/services/sideMenus/bip-partners.svg',
    href: '',
  },
]

export const topMenus = [
  {
    id: 1,
    name: 'Coperator / Mid-Market Enterprise',
    icon: '/menus/services/topMenus/people-top-card.svg',
    href: '',
  },
  {
    id: 2,
    name: 'Founded Startups',
    icon: '/menus/services/topMenus/school.svg',
    href: '',
  },
  {
    id: 3,
    name: 'Entrepreneur',
    icon: '/menus/services/topMenus/home.svg',
    href: '',
  },
  {
    id: 4,
    name: 'Foriegn Associates',
    icon: '/menus/services/topMenus/peoples-two.svg',
    href: '',
  },
]

export const subMenus = [
  [
    { title: 'How to patent', bold: true, division: false, href: '' },
    { title: 'Patent benefits', bold: false, division: false, href: '' },
    { title: '', bold: false, division: true, href: '' },
    { title: 'Patent search', bold: true, division: false, href: '' },
    {
      title: 'International patent search',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'International-type search',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Australian patent search',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Freedom-to-operate patent search',
      bold: false,
      division: false,
      href: '',
    },
    { title: '', bold: false, division: true },
    { title: 'Registered design', bold: true, division: false, href: '' },
    {
      title: 'Registered design application',
      bold: false,
      division: false,
      href: '',
    },
    { title: 'Design disputes', bold: false, division: false, href: '' },
    { title: '', bold: false, division: true, href: '' },
    { title: 'Other patent services', bold: true, division: false, href: '' },
    { title: 'Inovation patents', bold: false, division: false, href: '' },
    { title: '', bold: false, division: true, href: '' },
  ],
  [
    { title: 'Ip strategy', bold: true, division: false, href: '' },
    { title: 'Ip audit', bold: false, division: false, href: '' },
    { title: 'Ip vaulation', bold: false, division: false, href: '' },
    { title: '', bold: false, division: true, href: '' },
    {
      title: 'Patent opositions & dispites',
      bold: true,
      division: false,
      href: '',
    },
    { title: 'Patent opositions', bold: false, division: false, href: '' },
    { title: 'Patent itigation', bold: false, division: false, href: '' },
    { title: '', bold: false, division: true },
    { title: 'Other patent services', bold: false, division: false, href: '' },
    { title: 'Inovation patents', bold: false, division: false, href: '' },
    { title: '', bold: false, division: true },
    {
      title: 'Patent opositions & dispites',
      bold: true,
      division: false,
      href: '',
    },
    { title: 'Patent opositions', bold: false, division: false, href: '' },
    { title: 'Patent itigation', bold: false, division: false, href: '' },
  ],
  [
    {
      title: 'Australian patent process',
      bold: true,
      division: false,
      href: '',
    },
    {
      title: 'International-type patent search',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'PCT internationals patent applications',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'National phase patent application',
      bold: false,
      division: false,
      href: '',
    },
    { title: '', bold: false, division: true, href: '' },
    {
      title: 'Australian patent process',
      bold: true,
      division: false,
      href: '',
    },
    {
      title: 'International-type patent search',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'PCT internationals patent applications',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'National phase patent application',
      bold: false,
      division: false,
      href: '',
    },
    { title: '', bold: false, division: true, href: '' },
  ],
]

export const subMenus1 = [
  [
    {
      title: 'Chemical, biotech & pharmaceutical patents',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Civil engineering & construction patents',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Consumer product patents',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Electrical engineering & electronics patents',
      bold: false,
      division: false,
      href: '',
    },
    { title: 'Fintech patents', bold: false, division: false, href: '' },
    { title: 'Medical device patents', bold: false, division: false, href: '' },
    {
      title: 'Physics & optical engineering patents',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Software, apps & computer patents',
      bold: false,
      division: false,
      href: '',
    },
    { title: '', bold: false, division: true, href: '' },
  ],
]

export const subMenus2 = [
  [
    { title: 'HOW TO TRADE MARK', bold: true, division: false, href: '' },
    {
      title: 'Brand name vs trade mark',
      bold: false,
      division: false,
      href: '',
    },
    { title: 'Choosing a brand name', bold: false, division: false, href: '' },
    {
      title: 'Trade mark registration benefits',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'The role of Australian trade mark attorneys',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Domain names and trade marks',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Hashtags and trade marks',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Signs that cannot be protected as a trade mark',
      bold: false,
      division: false,
      href: '',
    },
    { title: '', bold: false, division: true, href: '' },
    {
      title: 'INTERNATIONAL TRADE MARK APPLICATION',
      bold: true,
      division: false,
      href: '',
    },
    {
      title: 'Madrid Protocol international trade mark application',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'International trade mark management and renewal',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Trade marks in other countries',
      bold: false,
      division: false,
      href: '',
    },
    { title: '', bold: false, division: true, href: '' },
  ],
  [
    { title: 'TRADE MARK PREPARATION', bold: true, division: false, href: '' },
    { title: 'Types of trade marks', bold: false, division: false, href: '' },
    {
      title: 'Special types of trade marks',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Classes of goods and/or services',
      bold: false,
      division: false,
      href: '',
    },
    { title: 'Trade mark search', bold: false, division: false, href: '' },
    { title: '', bold: false, division: true, href: '' },
    {
      title: 'TRADE MARK OPPOSITIONS & DISPUTES',
      bold: true,
      division: false,
      href: '',
    },
    { title: 'Trade mark opposition', bold: false, division: false, href: '' },
    {
      title: 'Grounds for trade mark opposition',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Evidence of Use preparation',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Other types of oppositions',
      bold: false,
      division: false,
      href: '',
    },
    { title: 'Trade mark disputes', bold: false, division: false, href: '' },
    {
      title: 'Trade mark infringement',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Trade mark enforcement and defence',
      bold: false,
      division: false,
      href: '',
    },
    { title: 'Trade mark litigation', bold: false, division: false, href: '' },
    { title: '', bold: false, division: true, href: '' },
  ],
  [
    {
      title: 'TRADE MARK REGISTRATION PROCESS',
      bold: true,
      division: false,
      href: '',
    },
    {
      title: 'Australian trade mark application',
      bold: false,
      division: false,
      href: '',
    },
    { title: 'Trade mark examination', bold: false, division: false, href: '' },
    { title: 'Trade mark acceptance', bold: false, division: false, href: '' },
    { title: 'Trade mark publication', bold: false, division: false, href: '' },
    { title: 'Trade mark maintenance', bold: false, division: false, href: '' },
    { title: 'Trade mark amendment', bold: false, division: false, href: '' },
    { title: 'Trade mark renewal', bold: false, division: false, href: '' },
    { title: '', bold: false, division: true },
  ],
]

export const subMenus3 = [
  [
    {
      title: 'PATENT OPPOSITIONS & DISPUTES',
      bold: true,
      division: false,
      href: '',
    },
    {
      title: 'Patent opposition',
      bold: false,
      division: false,
      href: '',
    },
    { title: 'Patent litigation', bold: false, division: false, href: '' },
    { title: '', bold: false, division: true, href: '' },
  ],
  [
    {
      title: 'TRADE MARK OPPOSITIONS & DISPUTES',
      bold: true,
      division: false,
      href: '',
    },
    {
      title: 'Australian trade mark application',
      bold: false,
      division: false,
      href: '',
    },
    { title: 'Trade mark opposition', bold: false, division: false, href: '' },
    {
      title: 'Grounds for trade mark opposition',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Evidence of Use preparation',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Other types of oppositions',
      bold: false,
      division: false,
      href: '',
    },
    { title: 'Trade mark disputes', bold: false, division: false, href: '' },
    {
      title: 'Trade mark infringement',
      bold: false,
      division: false,
      href: '',
    },
    {
      title: 'Trade mark enforcement and defence',
      bold: false,
      division: false,
      href: '',
    },
    { title: 'Trade mark litigationt', bold: false, division: false, href: '' },
    { title: '', bold: false, division: true, href: '' },
  ],
]

export const subMenus4 = [
  [
    { title: 'BIP Capital Partners', bold: false, division: false, href: '' },
    { title: '', bold: false, division: true, href: '' },
  ],
  ,
]
