name: Generate sitemap and robots.txt 
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: /
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Generate sitemap and robots.txt
        run: yarn next-sitemap